import os, uuid, datetime, json

class Connection():
    """
    This class gets generated by the database handler and is used for handling queries and interactions with the database
    """
    supported_adapters = ['esvi', 'sqlite3']


    def __init__(self, database_path):
        self.database_path = database_path
        self.database_dir = os.path.dirname(database_path)
        self.session_id = str(uuid.uuid4())

        print("Database type {}".format(database_path.split('.')))
        if not database_path.split('.')[-1] in Connection.supported_adapters:
            raise Exception("Unsupported database type")

        self.database_type = database_path.split('.')[-1]


    def get_path(self):
        return self.database_path

    def get_database_type(self):
        print("DB type is {}".format(self.database_type))
        return self.database_type
